### ISSUE TITLE
Fizz and buzz images are not shown :(

### ISSUE THREAD

**Issue by milyiyo** [jlorenzoC/FizzBuzz#1]
Hi @jlorenzoC,

Maybe this is something that happens only to me, but I cannot see the images of the drink and buzz :)

Check this screenshot:

![image](https://user-images.githubusercontent.com/8120990/129632038-8b46f30c-5754-43fd-95f4-3427b7cb8d11.png)

**Comment by jlorenzoC** [comment]
Hi @milyiyo, thanks for comment 😃. I solved it but I haven't published it yet (also doing some refactoring). Well, certainly it has to be with the way the pics are referenced when the project gets built in development environment mode, and when it gets built for production due my configs.

As you can see in that screenshot the app is trying to reach the pics at <server.domain>/assets/.. whereas the fact is that, when the project gets built for prod., the assets folder is created under this new folder called fizzbuzz, so in this scenario the correct url should be <server.domain>/fizzbuzz/assets/... 

I worked around and solved this using environment variables provided by environment.ts and environment.prod.ts files. Maybe there are others solutions to this, tho. but I decided to stick with this one in order to not find me myself touching others angular behind the scenes configs files. Here at the [Angular docs](https://angular.io/guide/build) more info related.

I'll post some updates soon, so you can see the pics of the drinks and the others haha 😃. I'll let you know when it's done.
