### ISSUE TITLE
Change the background-color of your cards with even number

### ISSUE THREAD

**Issue by OrlandoYero** [jlorenzoC/FizzBuzz#3]
Preferred color  "floralwhite"

**Comment by jlorenzoC** [comment]
@OrlandoYero , that's a good feature that will be great to show to the user in order to easily let them know which number is also even. Maybe using some kind of legend with colors, in this case something like this maybe:

![even number feature](https://user-images.githubusercontent.com/43883758/134220315-74ad96dd-2228-4563-aa04-5aa5090e36de.png)

**Comment by OrlandoYero** [comment]
I like that, but i'm disagree with the color. Please change it.
